version: 2
updates:
  - package-ecosystem: "npm"
    directory: "ch9_release/src/Tailwind.Traders.Web/ClientApp"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "ch8_packages/npm"
    schedule:
      interval: "daily"
    labels:
      - "ch8_npm"
    assignees:
      - "jvizuetazivra"
    open-pull-requests-limit: 2    