version: 2
updates:
  - package-ecosystem: "npm"
    directory: "ch9_release/src/Tailwind.Traders.Web/ClientApp"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "ch8_packages/npm"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2

  - package-ecosystem: "nuget"
    directory: "ch9_release/src/Tailwind.Traders.Web"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "nuget"
    assignees:
      - "jvizuetazivra"      
    open-pull-requests-limit: 3